package com.yongjun.stock.dao;

import com.yongjun.stock.entity.Company;

public interface CompanyDao {
    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int deleteByPrimaryKey(Long id);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int insert(Company record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int insertSelective(Company record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    Company selectByPrimaryKey(Long id);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int updateByPrimaryKeySelective(Company record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int updateByPrimaryKey(Company record);
}