package com.yongjun.stock.dao;

import com.yongjun.stock.entity.CustomerBalanceLog;

public interface CustomerBalanceLogDao {
    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int deleteByPrimaryKey(Long id);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int insert(CustomerBalanceLog record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int insertSelective(CustomerBalanceLog record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    CustomerBalanceLog selectByPrimaryKey(Long id);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int updateByPrimaryKeySelective(CustomerBalanceLog record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int updateByPrimaryKey(CustomerBalanceLog record);
}