package com.yongjun.stock.dao;

import com.yongjun.stock.entity.Customer;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CustomerDao {

    /**
     * Comment is created by lyl on 2017/10/24 下午2:50.
     *
     * 查找用户是否存在
     */
    Customer findCustomerLoginInfo(@Param("phoneNo") String phoneNo);

    /**
     * Comment is created by lyl on 2017/10/24 下午3:05.
     *
     * 测试
     */
    List<Customer> findCustomerInfo();

    List<Customer> selectByCondition(Customer customer);

    Customer selectByPhone(@Param("phoneNo") String phoneNo);

    int updatePassword(@Param("phoneNo") String phoneNo, @Param("oldPassword") String oldPassword, @Param("newPassword") String newPassword);

    int updateByPhone(Customer customer);

    /**
     *
     * generated by  mybatis generator 2017-10-27
     */
    int insert(Customer record);

    /**
     *
     * generated by  mybatis generator 2017-10-27
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     *
     * generated by  mybatis generator 2017-10-27
     */
    Customer selectByPrimaryKey(Long id);


}