package com.yongjun.stock.dao;

import com.yongjun.stock.entity.CustomerCard;
import java.util.List;

public interface CustomerCardDao {
    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int deleteByPrimaryKey(Long id);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int insert(CustomerCard record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int insertSelective(CustomerCard record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    CustomerCard selectByPrimaryKey(Long id);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int updateByPrimaryKeySelective(CustomerCard record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int updateByPrimaryKey(CustomerCard record);

    /**
     * 根据查询条件查询用户卡信息
     * @param customerCard
     * @return
     */
    List<CustomerCard> selectByCondition(CustomerCard customerCard);
}