package com.yongjun.stock.dao;

import com.yongjun.stock.entity.Order;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDao {

  /**
   * generated by  mybatis generator 2017-10-26
   */
  int deleteByPrimaryKey(Long id);

  /**
   * generated by  mybatis generator 2017-10-26
   */
  int insert(Order record);

  /**
   * generated by  mybatis generator 2017-10-26
   */
  int insertSelective(Order record);

  /**
   * generated by  mybatis generator 2017-10-26
   */
  Order selectByPrimaryKey(Long id);

  /**
   * generated by  mybatis generator 2017-10-26
   */
  int updateByPrimaryKeySelective(Order record);

  /**
   * generated by  mybatis generator 2017-10-26
   */
  int updateByPrimaryKey(Order record);

  /**
   * 根据不同查询条件查询策略
   */
  List<Order> selectByCondition(Order order);

  int updateStopPrice(Order order);

  /**
   * 查询历史订单
   */
  List<Order> selectHisOrder(@Param("companyId") Long companyId,
                             @Param("customerId") Long customerId);

}