package com.yongjun.stock.dao;

import com.yongjun.stock.entity.OrderDelay;

public interface OrderDelayDao {
    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int deleteByPrimaryKey(Long id);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int insert(OrderDelay record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int insertSelective(OrderDelay record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    OrderDelay selectByPrimaryKey(Long id);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int updateByPrimaryKeySelective(OrderDelay record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int updateByPrimaryKey(OrderDelay record);
}