package com.yongjun.stock.dao;

import com.yongjun.stock.entity.SmsLog;

public interface SmsLogDao {
    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int deleteByPrimaryKey(Long id);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int insert(SmsLog record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int insertSelective(SmsLog record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    SmsLog selectByPrimaryKey(Long id);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int updateByPrimaryKeySelective(SmsLog record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int updateByPrimaryKey(SmsLog record);
}