package com.yongjun.stock.dao;

import com.yongjun.stock.entity.StockRecommend;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockRecommendDao {
    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int deleteByPrimaryKey(Long id);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int insert(StockRecommend record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int insertSelective(StockRecommend record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    StockRecommend selectByPrimaryKey(Long id);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int updateByPrimaryKeySelective(StockRecommend record);

    /**
     *
     * generated by  mybatis generator 2017-10-26
     */
    int updateByPrimaryKey(StockRecommend record);

    List<StockRecommend> selectByCompany(@Param("companyId") Long companyId);
}